import { Trade, MarketTickerItem, TradingRule, ChecklistItem } from '../types/trade';

export const INITIAL_TICKER: MarketTickerItem[] = [
  { symbol: 'NIFTY FIN', name: 'Nifty Fin Service', value: 23890.45, change: -59.70, changePercent: -0.25 },
  { symbol: 'NIFTY DEF', name: 'Nifty Ind Defence', value: 7640.10, change: -32.15, changePercent: -0.42 },
  { symbol: 'NIFTY ENG', name: 'Nifty Energy', value: 39450.80, change: -19.70, changePercent: -0.05 },
  { symbol: 'NIFTY INFRA', name: 'Nifty Infra', value: 8920.30, change: -41.05, changePercent: -0.46 },
  { symbol: 'NIFTY CD', name: 'NIFTY CONSR DURBL', value: 38400.15, change: 122.90, changePercent: +0.32 },
  { symbol: 'BANKNIFTY', name: 'Nifty Bank', value: 49820.60, change: -120.40, changePercent: -0.24 },
  { symbol: 'REALTY', name: 'Nifty Realty', value: 1045.20, change: 13.70, changePercent: +1.33 },
  { symbol: 'NIFTY 50', name: 'Nifty 50', value: 23450.35, change: 105.50, changePercent: +0.45 },
  { symbol: 'SENSEX', name: 'BSE Sensex', value: 77210.80, change: 295.40, changePercent: +0.38 }
];

export const INITIAL_TRADES: Trade[] = [
  {
    id: 'tr-1',
    date: '2026-05-18',
    time: '10:15',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NIFTY-MAY2026-23400-PE',
    direction: 'Long',
    entryPrice: 145.65,
    exitPrice: 149.38,
    quantity: 950,
    totalAmount: 138367.5,
    stopLoss: 142.00,
    target: 155.00,
    pnl: 3543.50,
    fees: 5.28,
    netPnl: 3538.22,
    pnlPercent: 2.56,
    riskReward: '1:1.41',
    strategy: 'Breakout',
    outcome: 'Partial Success',
    notes: 'Clean range breakout on 5-min chart with strong volume surge.',
    analysis: 'Price broke consolidation during morning session. Booked 70% at first resistance.',
    emotion: 'Disciplined',
    confidence: 85,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Good execution, partial profits safeguarded against sudden pullbacks.',
    createdAt: '2026-05-18T10:15:00.000Z'
  },
  {
    id: 'tr-2',
    date: '2026-05-13',
    time: '09:45',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'SENSEX-MAY2026-74300-PE',
    direction: 'Long',
    entryPrice: 253.97,
    exitPrice: 399.27,
    quantity: 100,
    totalAmount: 25397,
    stopLoss: 236.00,
    target: 400.00,
    pnl: 14530.00,
    fees: 36.29,
    netPnl: 14493.71,
    pnlPercent: 57.21,
    riskReward: '1:8.07',
    strategy: 'Breakout',
    outcome: 'Full Success',
    notes: 'Major breakdown on weekly support level. Huge momentum.',
    analysis: 'Heavy call writing observed at 74500 strikes. Massive drop followed as expected.',
    emotion: 'Calm',
    confidence: 95,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Patience in letting winners run gives asymmetric R:R payoffs.',
    createdAt: '2026-05-13T09:45:00.000Z'
  },
  {
    id: 'tr-3',
    date: '2026-05-12',
    time: '11:30',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NIFTY-MAY2026-23700-PE',
    direction: 'Long',
    entryPrice: 58.70,
    exitPrice: 91.40,
    quantity: 325,
    totalAmount: 19077.5,
    stopLoss: 52.00,
    target: 90.00,
    pnl: 10627.50,
    fees: 27.07,
    netPnl: 10600.43,
    pnlPercent: 55.71,
    riskReward: '1:4.88',
    strategy: 'Breakout',
    outcome: 'Full Success',
    notes: 'Triangular pattern compression breakout on VWAP bounce.',
    analysis: 'VWAP held strong twice before giving explosive downside move.',
    emotion: 'Confident',
    confidence: 90,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Triangular compressions near VWAP have high probability.',
    createdAt: '2026-05-12T11:30:00.000Z'
  },
  {
    id: 'tr-4',
    date: '2026-05-12',
    time: '14:10',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NIFTY-MAY2026-23600-PE',
    direction: 'Long',
    entryPrice: 43.37,
    exitPrice: 45.75,
    quantity: 1920,
    totalAmount: 83270.4,
    stopLoss: 41.00,
    target: 50.00,
    pnl: 4569.60,
    fees: 3.83,
    netPnl: 4565.77,
    pnlPercent: 5.49,
    riskReward: '1:1.01',
    strategy: 'Breakout',
    outcome: 'Partial Success',
    notes: 'Quick scalp on expiry afternoon.',
    analysis: 'Volume spike before 2:30 PM momentum burst.',
    emotion: 'Disciplined',
    confidence: 80,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Quick exit was smart before theta decay kicked in.',
    createdAt: '2026-05-12T14:10:00.000Z'
  },
  {
    id: 'tr-5',
    date: '2026-05-08',
    time: '09:15',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NO_TRADE',
    direction: 'Long',
    entryPrice: 0,
    exitPrice: 0,
    quantity: 0,
    totalAmount: 0,
    stopLoss: 0,
    target: 0,
    pnl: 0,
    fees: 0,
    netPnl: 0,
    pnlPercent: 0,
    riskReward: 'N/A',
    strategy: 'Discipline Rule',
    outcome: 'Full Success',
    isNoTradeDay: true,
    notes: 'Choppy sideways market with no clean setups. Decided to sit on cash.',
    analysis: 'VIX dropped 4% and market stayed in a 30 point tight range all day.',
    emotion: 'Disciplined',
    confidence: 100,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Preserving capital during chop is as rewarding as a win.',
    createdAt: '2026-05-08T09:15:00.000Z'
  },
  {
    id: 'tr-6',
    date: '2026-05-04',
    time: '13:20',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NIFTY-MAY2026-24200-PE',
    direction: 'Long',
    entryPrice: 91.58,
    exitPrice: 88.04,
    quantity: 1325,
    totalAmount: 121343.5,
    stopLoss: 94.00,
    target: 80.00,
    pnl: -4690.04,
    fees: 0,
    netPnl: -4690.04,
    pnlPercent: -3.87,
    riskReward: '1:0.75',
    strategy: '9&15 Ema',
    outcome: 'Mistake',
    notes: 'Entered without candle close confirmation.',
    analysis: 'Chased the move after 9 EMA crossover without waiting for 15-min retest.',
    emotion: 'FOMO',
    confidence: 40,
    mistakes: ['FOMO Entry', 'No Clear Plan'],
    followedPlan: false,
    followedRisk: false,
    lessonLearned: 'Never enter before candle closes above/below EMA triggers.',
    createdAt: '2026-05-04T13:20:00.000Z'
  },
  {
    id: 'tr-7',
    date: '2026-04-29',
    time: '10:00',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'BANKNIFTY-APR2026-49000-CE',
    direction: 'Long',
    entryPrice: 320.50,
    exitPrice: 530.00,
    quantity: 150,
    totalAmount: 48075,
    stopLoss: 290.00,
    target: 520.00,
    pnl: 31425.00,
    fees: 42.00,
    netPnl: 31383.00,
    pnlPercent: 65.37,
    riskReward: '1:6.88',
    strategy: 'Breakout',
    outcome: 'Full Success',
    notes: 'Huge morning rally after banking earnings beats.',
    analysis: 'HDFC Bank & ICICI Bank both opened gap up and held day high.',
    emotion: 'Calm',
    confidence: 95,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Sector leader alignment gives best momentum continuation.',
    createdAt: '2026-04-29T10:00:00.000Z'
  },
  {
    id: 'tr-8',
    date: '2026-04-28',
    time: '11:15',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NIFTY-APR2026-23100-CE',
    direction: 'Long',
    entryPrice: 108.22,
    exitPrice: 121.74,
    quantity: 1200,
    totalAmount: 129864,
    stopLoss: 102.00,
    target: 125.00,
    pnl: 16224.00,
    fees: 28.50,
    netPnl: 16195.50,
    pnlPercent: 12.49,
    riskReward: '1:2.17',
    strategy: '9&15 Ema',
    outcome: 'Full Success',
    notes: 'Clean EMA crossover on 15m timeframe.',
    analysis: 'RSI divergence confirmed the bounce from 200 EMA support.',
    emotion: 'Disciplined',
    confidence: 88,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Follow system rules strictly.',
    createdAt: '2026-04-28T11:15:00.000Z'
  },
  {
    id: 'tr-9',
    date: '2026-04-25',
    time: '14:45',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'RELIANCE-EQ',
    direction: 'Short',
    entryPrice: 2950.00,
    exitPrice: 2990.00,
    quantity: 575,
    totalAmount: 1696250,
    stopLoss: 2970.00,
    target: 2900.00,
    pnl: -23000.00,
    fees: 81.13,
    netPnl: -23081.13,
    pnlPercent: -1.36,
    riskReward: '1:2.5',
    strategy: 'Pullback',
    outcome: 'Loss',
    notes: 'Failed breakdown pullback, turned into short squeeze.',
    analysis: 'Held short position even after SL hit hoping for reversal.',
    emotion: 'Greed',
    confidence: 30,
    mistakes: ['greed', 'Overleveraged'],
    followedPlan: false,
    followedRisk: false,
    lessonLearned: 'Always respect stop loss immediately. Never average down.',
    createdAt: '2026-04-25T14:45:00.000Z'
  },
  {
    id: 'tr-10',
    date: '2026-04-22',
    time: '10:30',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'TATAMOTORS-EQ',
    direction: 'Long',
    entryPrice: 980.00,
    exitPrice: 990.00,
    quantity: 615,
    totalAmount: 602700,
    stopLoss: 970.00,
    target: 1010.00,
    pnl: 6150.00,
    fees: 27.85,
    netPnl: 6122.15,
    pnlPercent: 1.02,
    riskReward: '1:3.0',
    strategy: 'Pullback',
    outcome: 'Partial Success',
    notes: 'Exited early out of fear, stock went to 1025 later.',
    analysis: 'Panic sold at first red 1-min candle despite no trend breach.',
    emotion: 'Anxious',
    confidence: 50,
    mistakes: ['Exited Too Early'],
    followedPlan: false,
    followedRisk: true,
    lessonLearned: 'Trust the stop loss level, avoid micro-managing on lower timeframes.',
    createdAt: '2026-04-22T10:30:00.000Z'
  },
  {
    id: 'tr-11',
    date: '2026-04-18',
    time: '13:00',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'TCS-EQ',
    direction: 'Short',
    entryPrice: 3820.00,
    exitPrice: 3845.00,
    quantity: 100,
    totalAmount: 382000,
    stopLoss: 3835.00,
    target: 3770.00,
    pnl: -2500.00,
    fees: 85.59,
    netPnl: -2585.59,
    pnlPercent: -0.65,
    riskReward: '1:3.33',
    strategy: 'Pullback',
    outcome: 'Loss',
    notes: 'Traded during midday lunch chop without clean volume.',
    analysis: 'Random trade taken out of boredom without pre-market plan.',
    emotion: 'Impatient',
    confidence: 35,
    mistakes: ['No Clear Plan', 'FOMO Entry'],
    followedPlan: false,
    followedRisk: true,
    lessonLearned: 'Avoid 12 PM - 1:30 PM lunchtime chop trading completely.',
    createdAt: '2026-04-18T13:00:00.000Z'
  },
  {
    id: 'tr-12',
    date: '2026-04-15',
    time: '09:20',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'INFY-EQ',
    direction: 'Long',
    entryPrice: 1420.00,
    exitPrice: 1480.00,
    quantity: 350,
    totalAmount: 497000,
    stopLoss: 1405.00,
    target: 1475.00,
    pnl: 21000.00,
    fees: 48.20,
    netPnl: 20951.80,
    pnlPercent: 4.23,
    riskReward: '1:4.0',
    strategy: 'Breakout',
    outcome: 'Full Success',
    notes: 'Gap & Go strategy on earnings reaction.',
    analysis: 'High relative volume (> 4x 30-day average) at open.',
    emotion: 'Disciplined',
    confidence: 92,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'High RVOL setups at open produce explosive trends.',
    createdAt: '2026-04-15T09:20:00.000Z'
  },
  {
    id: 'tr-13',
    date: '2026-04-11',
    time: '11:00',
    marketType: 'Indian',
    duration: 'Intraday',
    symbol: 'NIFTY-APR2026-22800-CE',
    direction: 'Long',
    entryPrice: 85.00,
    exitPrice: 135.00,
    quantity: 800,
    totalAmount: 68000,
    stopLoss: 72.00,
    target: 130.00,
    pnl: 40000.00,
    fees: 32.50,
    netPnl: 39967.50,
    pnlPercent: 58.82,
    riskReward: '1:3.85',
    strategy: '9&15 Ema',
    outcome: 'Full Success',
    notes: 'Perfect 9 EMA bounce on 5m chart after morning pullback.',
    analysis: 'Clean bullish engulfing candle on key support.',
    emotion: 'Calm',
    confidence: 96,
    mistakes: [],
    followedPlan: true,
    followedRisk: true,
    lessonLearned: 'Stick to A+ setups.',
    createdAt: '2026-04-11T11:00:00.000Z'
  }
];

export const INITIAL_RULES: TradingRule[] = [
  {
    id: 'rule-1',
    title: 'Never risk more than 1.5% of total capital on a single trade',
    description: 'Calculate position sizing before entering the order based on defined stop loss.',
    category: 'Risk',
    mandatory: true,
    active: true
  },
  {
    id: 'rule-2',
    title: 'Always place Hard Stop Loss in terminal immediately upon entry',
    description: 'Mental stop loss leads to hesitation and oversized drawdowns.',
    category: 'Risk',
    mandatory: true,
    active: true
  },
  {
    id: 'rule-3',
    title: 'Max 3 trades per day rule (Stop after 2 consecutive losses)',
    description: 'Prevents revenge trading and overtrading spiral during unfavourable market conditions.',
    category: 'Psychology',
    mandatory: true,
    active: true
  },
  {
    id: 'rule-4',
    title: 'Only trade defined setups (Breakout / EMA Crossover / Key Level Pullback)',
    description: 'No impulsive trades based on chatroom tips, social media noise, or unconfirmed spikes.',
    category: 'Execution',
    mandatory: true,
    active: true
  },
  {
    id: 'rule-5',
    title: 'No trading between 12:00 PM and 1:30 PM (Lunch chop zone)',
    description: 'Volume drops and false breakouts are highest during midday.',
    category: 'Execution',
    mandatory: false,
    active: true
  },
  {
    id: 'rule-6',
    title: 'Trail Stop Loss to Breakeven once 1:1.5 Risk Reward is reached',
    description: 'Lock in risk-free trade and let runners capture oversized profits.',
    category: 'Risk',
    mandatory: false,
    active: true
  }
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  { id: 'chk-1', title: 'Checked Global Indices & SGX / GIFT Nifty sentiment', category: 'Pre-Market', completed: true },
  { id: 'chk-2', title: 'Identified Key Daily Support & Resistance levels', category: 'Pre-Market', completed: true },
  { id: 'chk-3', title: 'Verified no major high-impact economic news during market hours', category: 'Pre-Market', completed: true },
  { id: 'chk-4', title: 'Setup meets all Entry Checklist criteria with volume confirmation', category: 'Execution', completed: false },
  { id: 'chk-5', title: 'Position size calculated accurately against stop loss distance', category: 'Execution', completed: false },
  { id: 'chk-6', title: 'Mindset is calm, disciplined, and free from FOMO or greed', category: 'Execution', completed: false },
  { id: 'chk-7', title: 'Logged all trades with screenshots and psychological notes', category: 'Post-Market', completed: false },
  { id: 'chk-8', title: 'Reviewed mistakes and updated trading rules adherence score', category: 'Post-Market', completed: false }
];
